kibana:

  build: ./kibana
  restart: always
  hostname: kibana
  links:
    - "elasticsearch"

elasticsearch:

  build: ./elasticsearch
  restart: always
  hostname: elasticsearch
  ports:
    - "9200:9200"
    - "9300:9300"
  volumes:
    - "/data:/data"

logstash:

  build: ./logstash
  restart: always
  hostname: logstash
  ports:
    - "4545:4545"
    - "4546:4546"
  volumes:
    - "/data:/data"

nginx:

  build: ./nginx
  restart: always
  hostname: nginx
  ports:
    - "80:80"
  links:
    - "kibana"
