kibana:
  build: ./kibana
  restart: on-failure
  hostname: kibana
  links:
    - "elasticsearch"

elasticsearch:
  build: ./elasticsearch
  restart: on-failure
  hostname: elasticsearch
  ports:
    - "127.0.0.1:9200:9200"
  expose:
    - "9200"
    - "9300"
  volumes:
    - "/data:/data"

logstash:
  build: ./logstash
  restart: on-failure
  hostname: logstash
  ports:
    - "4545:4545"
    - "4545/udp:4545/udp"
  volumes:
    - "/data:/data"
  links:
    - "elasticsearch"

nginx:
  build: ./nginx
  restart: on-failure
  hostname: nginx
  ports:
    - "80:80"
  links:
    - "kibana"
    - "sandbox"

sandbox:
  image: wordpress
  links:
    - db:mysql
  ports:
    - 80

db:
  image: mysql
  environment:
    MYSQL_ROOT_PASSWORD: MYSQLpass## "kibana"
